<div class="container jumbotron">
    <?php if( isset($_SERVER['HTTP_REFERER'] ) ) { ?>
        <div class="row">
            <div class="col-sm-1"></div>
            <a href="<?php echo $_SERVER['HTTP_REFERER']?>" class="btn btn-primary" style="border: 0px;">Back</a>
        </div>
    <?php } ?>
    <h1 class="display-3 text-center" style="color: #2C3E50">Add Post</h1>
    <form method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>">
        <div class="row mt-5">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <div class="form-group row">
                    <label class="col-sm-2" for="">Title:</label>
                    <input type="text" name="title" class="col-sm-10 form-control">
                </div>
                <div class="form-group row">
                    <label class="col-sm-2" for="">Author:</label>
                    <input type="text" name="author" class="col-sm-10 form-control">
                </div>
                <div class="form-group row">
                    <label class="col-sm-2" for="">Body:</label>
                    <textarea rows="6" type="text" name="body" class="col-sm-10 form-control"></textarea>
                </div>
                <!-- <div class="form-group row">
                    <label class="col-sm-2" for="exampleFormControlFile1">Add Image:</label>
                    <input type="file" class="col-sm-10 form-control-file" id="exampleFormControlFile1">
                </div> -->
                <input type="hidden" name="userId" value="<?php echo $_SESSION['loggedInId']; ?>">
                <div class="row mt-5">
                    <div class="col-sm-5"></div>
                    <input type="submit" name="submit" class="btn btn-primary sm-col-2" value="Submit">
                    <div class="col-sm-5"></div>
                </div>
            </div>
            <div class="col-sm-1"></div>
        </div> 
    </form>
</div>