<div class="imageCover masthead">
    <div class="cover-container d-flex p-3 flex-column text-center index-box">
        <div class="container">
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-8 ">
                    <div class="container innerBox">
                        <h1 class="cover-heading text-danger">Publish your passions, your way</h3>
                        <p class="lead text-primary"><strong>Create a unique and beautiful blog. It’s easy and free.</strong></p>
                        <p class="lead">
                            <a href="signup.php" class="btn btn-lg btn-warning">Join Now</a>
                        </p>
                    </div>
                </div>
                <div class="col-sm-2"></div>
            </div>
        </div>
    </div>
</div>