<div class="loginImage"></div>
<div class="row login-box" style="margin-top:100px">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="container jumbotron jumbo text-light text-center">
            <h1>Login</h1>
            <p class="lead">Use this from to log into your Account</p>

            <?php 
            if( isset( $_GET['alert'] ) ) {
                echo $alertMessage;
            }
            ?>

            <form class="form"  method="POST" action="<?php echo htmlspecialchars( $_SERVER['PHP_SELF'] ); ?>">
                
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <label for="login-email" class="col-md-2 col-form-label">Email</label>
                    <div class="col-md">
                        <input type="text" class="form-control" name="email" <?php if(isset($_POST['login'])) { ?> value=" <?php echo $formEmail; } ?>" id="login-email" placeholder="Enter email">
                    </div>
                    <div class="col-md-2"></div>
                </div>

                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <label for="login-password" class="col-md-2 col-form-label">Password</label>
                    <div class="col-md">
                    <input type="password" class="form-control" id="login-password" name="password" placeholder="Enter Password">
                    </div>
                    <div class="col-md-2"></div>
                </div>

                <?php if(isset($_POST['login'])){
                    echo $loginError;
                }
                ?>

                <input type="submit" name="login" class="btn btn-info   " value="Login"> 
            </form>
            <hr>
            <p class="lead">Not a member yet? <a class="" href="signup.php">Join Now</a></p>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>