<div class="row" style="margin-top:100px">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="container jumbotron jumbo text-light text-center">
            <p class="lead">You've been Logged Out! See you Next time...</p>
            <br>
            <a type="button" class="btn btn-default" href='index.php'>Home</a>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>