<!-- Post Section -->
<div class="container jumbotron">
    <div class="d-flex">
        <div class="p-2">
            <a href="<?php echo $_SERVER['HTTP_REFERER']?>" class="btn btn-primary" style="border: 0px;"><i class="fas fa-caret-left"></i> Back</a>
        </div>
        <?php if( $_SESSION ) if( $_SESSION['loggedInId'] == $post['userId'] ) { ?>
            <div class="ml-auto p-2">
                <a href="editPost.php?id=<?php echo $post['id']; ?>" class="btn btn-primary" style="border: 0px;"><i class="fas fa-edit"></i></a>
            </div>
            <form class="p-2" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                <a data-toggle="modal" data-target="#deleteModal" value="Delete Post" class="btn btn-danger text-light" style="border: 0px;"><i class="fas fa-trash"></i></a>
            </form>
        <?php } ?>
    </div>
    
    <h1 class="display-5 text-center" style="color: #2C3E50"><?php echo $post['title']; ?></h1>
    <hr style="height:2px; background-color: #2C3E50">
    <div class="container">
        <small class="lead" style="font-size: 15px; font-style: italic">Created at <?php echo $post['created_at']; ?> by <?php echo $post['author']; ?></small>
        <?php if( isset( $_GET['alert'] ) ) { echo $alertMessage; } ?>
        <p class="lead"><?php echo $post['body']; ?></p>
    </div>
    <hr class="mt-5"style="width:75%">
    <br>
</div>

<!-- Comments Section -->
<div class="container jumbotron">
    <?php if( $alertComent != NULL ) {
        echo $alertComent;
    } ?>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <h3 class="display-5 text-center" style="color: #2C3E50">Comments</h3>
            <hr style="width:60%; background: rgba(44, 62, 80, 0.1)">
            <?php
            if( $emptyComments == NULL ) {
                foreach($comments as $comment) : ?>
                <div class="container row">
                    <div class="col-sm-2">
                        <strong><?php echo $comment['username'].': '; ?> </strong>
                        <br>
                        <small>(<?php echo $comment['created_at'].': '; ?>)</small>   
                    </div>
                    <div class="col-sm-8"><?php echo $comment['comment']; ?></div>
                    
                    <hr style="width:100%; background: rgba(44, 62, 80, 0.1)">
                </div>
            <?php endforeach; } ?>
        </div>
        <div class="col-sm-1"></div>
    </div>
    
    <!-- Collapse Comments -->
    <button type="button" class="btn btn-primary" style="margin-left:112px;" data-toggle="collapse" data-target="#collapseComments" aria-expanded="false" aria-controls="collapseComments">Add Comment</button>
    <div class="row collapse mt-5" id="collapseComments">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <form action="<?php echo $_SERVER['PHP_SELF'].'?id='.$id; ?>" class="row" method="POST">
                <div class="form-group col-sm row">
                    <label class="col-sm-2 text-center">Comment:</label>
                    <textarea class="form-control col-sm-10" name="message" id="" rows="1"></textarea>
                </div>
                <input type="hidden" name="userId" value="<?php echo $_SESSION['loggedInId']; ?>">
                <input type="hidden" name="postId" value="<?php echo $id; ?>">
                <input type="hidden" name="username" value="<?php echo $_SESSION['loggedInUser']; ?>">
                <input type="submit" name="addComment" class="form-group ml-1 btn btn-primary" value="Add">
                    
            </form>
        </div>
        <div class="col-sm-1"></div>
    </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content bg-primary">
            <div class="modal-header text-light">
                <h5 class="modal-title" id="exampleModalLabel">Delete Client</h5>
                <button type="button" class="close btn btn-secondary" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body bg-light text-primary">
                <p>Are you sure you want to delete?</p>
                <br>
            </div>
            <div class="modal-footer bg-secondary">
                <form class="p-2" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                    <input type="hidden" name="delete_id" value="<?php echo $post['id']; ?>">
                    <input type="submit" name="delete" class="btn btn-danger btn-sm" value="Yes">
                    <a type="button" class="btn btn-primary text-light btn-sm" data-dismiss="modal" >No</a>
                </form>
            </div>
        </div>
    </div>
</div>